server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "multitenant_messaging"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

rabbitmq:
  host: "rabbitmq"
  port: 5672
  user: "guest"
  password: "guest"
  vhost: "/"
  connection_timeout: 30s
  heartbeat: 10s

jwt:
  secret: "your-secret-key-change-in-production"
  expiration_hours: 24

consumer:
  default_workers: 3
  max_workers: 10
  worker_buffer_size: 100
  retry_attempts: 3
  retry_delay: 5s

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info"
  format: "json" 